# Generated by Django 4.1.3 on 2022-11-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('contrasenia', models.CharField(max_length=200)),
                ('rut_cliente', models.IntegerField()),
                ('dv_cliente', models.CharField(max_length=5)),
                ('fecha_alta', models.DateField()),
                ('razon_social', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('ap_paterno', models.CharField(blank=True, max_length=50, null=True)),
                ('ap_materno', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_postal', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=100)),
                ('comuna', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('pais', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleSolicitud',
            fields=[
                ('detalle_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=50)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('cantidad', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detalle_solicitud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('solicitud_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=10)),
                ('fecha_solicitud', models.DateField()),
            ],
            options={
                'db_table': 'solicitud',
                'managed': False,
            },
        ),
    ]
