# Generated by Django 4.1.3 on 2022-11-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('contrato_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=10)),
                ('rol_contrato', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_ini', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contrato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('oferta_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=10)),
                ('uni_medida', models.CharField(max_length=20)),
                ('cantidad', models.FloatField()),
                ('precio', models.FloatField()),
                ('calidad', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'oferta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=50)),
                ('imagen_producto', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('productor_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('contrasenia', models.CharField(max_length=200)),
                ('razon_social', models.CharField(max_length=100)),
                ('rut_productor', models.BigIntegerField()),
                ('dv_productor', models.CharField(max_length=5)),
                ('fecha_alta', models.DateField()),
                ('direccion', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'productor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductorOferta',
            fields=[
                ('prod_ofer_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_oferta', models.DateField()),
            ],
            options={
                'db_table': 'productor_oferta',
                'managed': False,
            },
        ),
    ]
