# Generated by Django 4.1.3 on 2022-11-04 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('contrasenia', models.CharField(max_length=200)),
                ('rut_cliente', models.IntegerField()),
                ('dv_cliente', models.CharField(max_length=5)),
                ('fecha_alta', models.DateField()),
                ('razon_social', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('ap_paterno', models.CharField(blank=True, max_length=50, null=True)),
                ('ap_materno', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_postal', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=100)),
                ('comuna', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('pais', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('detalle_venta_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cantidad', models.FloatField()),
                ('precio_bruto', models.FloatField()),
                ('uni_medida', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'detalle_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('oferta_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=10)),
                ('uni_medida', models.CharField(max_length=20)),
                ('cantidad', models.FloatField()),
                ('precio', models.FloatField()),
                ('calidad', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'oferta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('producto', models.CharField(max_length=50)),
                ('imagen_producto', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('solicitud_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=10)),
                ('fecha_solicitud', models.DateField()),
            ],
            options={
                'db_table': 'solicitud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subasta',
            fields=[
                ('subasta_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=1)),
                ('precio', models.FloatField()),
                ('fecha_ini', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tipo_vehiculo', models.CharField(max_length=100)),
                ('peso_carga', models.FloatField()),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'subasta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('empresa_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('contrasenia', models.CharField(max_length=200)),
                ('razon_social', models.CharField(max_length=200)),
                ('rut_transporte', models.BigIntegerField()),
                ('dv_transporte', models.CharField(max_length=2)),
                ('fecha_alta', models.DateField()),
                ('direccion', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'transporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransSubasta',
            fields=[
                ('proceso_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=10)),
                ('fecha_oferta', models.DateField()),
                ('precio_ofertado', models.FloatField()),
            ],
            options={
                'db_table': 'trans_subasta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('transporte_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=10)),
                ('patente', models.CharField(max_length=20)),
                ('tipo_vehiculo', models.CharField(max_length=50)),
                ('carga_util', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'vehiculo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('venta_id', models.BigIntegerField(db_column='venta__id', primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=10)),
                ('tipo_venta', models.CharField(max_length=50)),
                ('total', models.FloatField()),
                ('fecha_venta', models.DateField()),
                ('impuestos', models.FloatField()),
            ],
            options={
                'db_table': 'venta',
                'managed': False,
            },
        ),
    ]
